version: '3'
services:
  postgres:
    restart: always
    container_name: 'postgres'
    image: 'postgres:12-alpine3.18'
    ports:
      - "5432:5432"
    env_file:
      - ./docker/postgres/pg.env
    volumes:
      - ./docker/postgres/volumes/data:/var/lib/postgresql/data
      - ./docker/postgres/scripts/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - backend
networks:
  backend:
    driver: bridge